"""Altera numero_parcela para String(20) e adiciona index

Revision ID: 8a9b5682cf7c
Revises: 53314bafe11d
Create Date: 2025-04-29 16:07:15.819817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9b5682cf7c'
down_revision = '53314bafe11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_parcelas', schema=None) as batch_op:
        batch_op.alter_column('numero_parcela',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_tbl_parcelas_numero_parcela'), ['numero_parcela'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_parcelas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_parcelas_numero_parcela'))
        batch_op.alter_column('numero_parcela',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
