"""Configuração inicial para Mysql

Revision ID: ec50cd8a955f
Revises: 
Create Date: 2025-05-12 09:36:04.126567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec50cd8a955f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_cidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_cidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_cidades_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_tbl_cidades_nome_cidade'), ['nome_cidade'], unique=False)

    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_tbl_users_username'), ['username'], unique=True)

    op.create_table('tbl_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.Column('conexao', sa.String(length=100), nullable=True),
    sa.Column('valor_mensalidade', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dia_cobranca', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['tbl_cidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_clientes_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_tbl_clientes_data_cadastro'), ['data_cadastro'], unique=False)
        batch_op.create_index(batch_op.f('ix_tbl_clientes_nome'), ['nome'], unique=False)

    op.create_table('tbl_parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cobranca_uuid', sa.String(length=36), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.String(length=20), nullable=False),
    sa.Column('total_parcelas', sa.Integer(), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'LIQUIDADA', 'CANCELADA', name='statusparcela'), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['tbl_clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_parcelas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_parcelas_cobranca_uuid'), ['cobranca_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_tbl_parcelas_data_vencimento'), ['data_vencimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_tbl_parcelas_numero_parcela'), ['numero_parcela'], unique=False)
        batch_op.create_index(batch_op.f('ix_tbl_parcelas_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_parcelas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_parcelas_status'))
        batch_op.drop_index(batch_op.f('ix_tbl_parcelas_numero_parcela'))
        batch_op.drop_index(batch_op.f('ix_tbl_parcelas_data_vencimento'))
        batch_op.drop_index(batch_op.f('ix_tbl_parcelas_cobranca_uuid'))

    op.drop_table('tbl_parcelas')
    with op.batch_alter_table('tbl_clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_clientes_nome'))
        batch_op.drop_index(batch_op.f('ix_tbl_clientes_data_cadastro'))
        batch_op.drop_index(batch_op.f('ix_tbl_clientes_ativo'))

    op.drop_table('tbl_clientes')
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_users_username'))
        batch_op.drop_index(batch_op.f('ix_tbl_users_email'))

    op.drop_table('tbl_users')
    with op.batch_alter_table('tbl_cidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_cidades_nome_cidade'))
        batch_op.drop_index(batch_op.f('ix_tbl_cidades_estado'))

    op.drop_table('tbl_cidades')
    # ### end Alembic commands ###
