"""Adiciona novos campos ao Cliente: ativo, contato, conexao, valor_mensalidade, dia_cobranca, obs

Revision ID: 13e87cfa9cd9
Revises: e1afb608f257
Create Date: 2025-04-29 10:49:41.605029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e87cfa9cd9'
down_revision = 'e1afb608f257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('contato', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('conexao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('valor_mensalidade', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('dia_cobranca', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('obs', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tbl_clientes_ativo'), ['ativo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_clientes_ativo'))
        batch_op.drop_column('obs')
        batch_op.drop_column('dia_cobranca')
        batch_op.drop_column('valor_mensalidade')
        batch_op.drop_column('conexao')
        batch_op.drop_column('contato')
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
