"""Adicionar os campos telefone e email

Revision ID: 55b8f0d469bf
Revises: 13e87cfa9cd9
Create Date: 2025-04-29 11:17:58.697449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b8f0d469bf'
down_revision = '13e87cfa9cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_clientes', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
