"""Adicionar modelo para autenticação

Revision ID: 5f74ab6a4d63
Revises: 8a9b5682cf7c
Create Date: 2025-05-05 17:08:27.721343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f74ab6a4d63'
down_revision = '8a9b5682cf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_tbl_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_users_username'))
        batch_op.drop_index(batch_op.f('ix_tbl_users_email'))

    op.drop_table('tbl_users')
    # ### end Alembic commands ###
